MxOnline/urls.py
# _*_ coding:utf-8 _*_
"""MxOnline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
import xadmin
#  用来处理静态文件
from django.views.static import serve
#  加载登录视图
from users.views import LoginView,RegisterView, AciveUserView,ForgetPwdView, ResetView,ModifyPwdView
from organization.views import OrgView
from MxOnline.settings import MEDIA_ROOT


urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    # 首页加载
    url('^$', TemplateView.as_view(template_name='index.html'), name='index'),
    # 登录页面
    url(r'^login/$', LoginView.as_view(), name='login'),
    # 注册页面
    url(r'register/$',RegisterView.as_view(), name='register'),
    # 验证码登录
    url(r'^captcha/', include('captcha.urls')),
    # 邮箱激活
    url(r'^active/(?P<active_code>.*)/$',AciveUserView.as_view(),name='user_active'),
    # 忘记密码
    url(r'^forget/$',ForgetPwdView.as_view(),name='forget_pwd'),
    # 重置密码
    url(r'^reset/(?P<active_code>.*)/$',ResetView.as_view(),name='reset_pwd'),
    # 重置密码表单 POST 请求
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name='modify_pwd'),
    # 课程机构url配置
    url(r'^org/', include('organization.urls', namespace='org')),
    # 课程列表url配置
    url(r'^course/', include('courses.urls', namespace='courses')),


    #  处理上传文件media的信息
    url(r'^media/(?P<path>.*)$',serve,{'document_root':MEDIA_ROOT})




]

apps/courses/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'bobby'
__date__ = '2017/5/18 10:15'

from django.conf.urls import url

from .views import CourseListView, CourseDetailView, CourseInfoView, CommentsView, AddCommentsView, VideoPlayView
urlpatterns = [
    # 课程列表页
    url(r'^list/$', CourseListView.as_view(), name='course_list'),
    # 课程详情页
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='course_detail'),
    # 视频列表页
    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name='course_info'),
    # 课程评论
    url(r'^comments/(?P<course_id>\d+)/$', CommentsView.as_view(), name='course_comment'),
    #  添加评论
    url(r'^add_comment/$', AddCommentsView.as_view(), name='add_comment'),
    #  添加课程视频
    url(r'^add_comment/$', VideoPlayView.as_view(), name='video_play'),

]

apps/organization/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'bobby'
__date__ = '2017/5/18 10:15'

from django.conf.urls import url

from .views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView,OrgTeacherView, AddFavView

from .views import TeacherView, TeacherDetailView
urlpatterns = [
    # 课程机构列表页
    url(r'^list/$', OrgView.as_view(), name='org_list'),
    url(r'^add_ask/$', AddUserAskView.as_view(),name='add_ask'),
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name='org_home'),
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name='org_course'),
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name='org_desc'),
    url(r'^teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name='org_teacher'),

    # 机构收藏
    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),

    # 讲师的列表页
    url(r'^teacher/list/$', TeacherView.as_view(), name='teacher_list'),
    # 讲师详情页
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='teacher_detail'),

]

apps/courses/models.py
# _*_ coding:utf-8 _*_
from datetime import datetime

from django.db import models

from organization.models import CourseOrg, Teacher

# Create your models here.


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name=u'课程机构', null=True, blank=True)
    name = models.CharField(max_length=52, verbose_name=u'课程名字')
    desc = models.CharField(max_length=300, verbose_name=u'课程描述')
    # 外键的值
    teacher = models.ForeignKey(Teacher, verbose_name=u'讲师', null=True, blank=True)
    detail = models.TextField(verbose_name=u'课程详情')
    degree = models.CharField(choices=(('cj', '初级'), ('zj', '中级'), ('gj', '高级')), max_length=2, verbose_name=u'难度')
    learn_times = models.IntegerField(default=0, verbose_name=u'学习时长(分钟数)')
    students = models.IntegerField(default=0, verbose_name=u'学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name=u'收藏人数')
    image = models.ImageField(upload_to='courses/%Y/%m', verbose_name=u'封面图', max_length=100)
    click_nums = models.IntegerField(default=0, verbose_name=u'点击数')
    is_banner = models.BooleanField(default=False, verbose_name=u'是否是轮播图')
    category = models.CharField(default='后端', max_length=20, verbose_name=u'课程类别')
    tag = models.CharField(default='', verbose_name=u'课程标签', max_length=10)
    youneed_konw = models.CharField(default='', max_length=300, verbose_name=u'课前须知')
    teacher_tell = models.CharField(default='', max_length=300, verbose_name=u'老师告诉你能学什么')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    #     定义章节数
    def get_zj_nums(self):
        return self.lesson_set.all().count()

        #获取学习这门课程的用户
    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        return self.lesson_set.all()

    def __unicode__(self):
        return self.name


# 章节信息
class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = '章节'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

    # 获取章节视频
    def get_lesson_video(self):
        return self.video_set.all()


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u'章节')
    name = models.CharField(max_length=100, verbose_name=u'视频名')
    url = models.URLField(max_length=200, verbose_name=u'访问地址', default='www.baidu.com')
    learn_times = models.IntegerField(default=0, verbose_name=u'视频时长(分钟数)')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

#  课程链接
class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'课件名')
    download = models.FileField(upload_to='course/resource/%Y/%m', verbose_name=u'资源文件', max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

apps/users/forms.py
# _*_ coding:utf-8 _*_
__author__ = 'bobby'
__date__ = '2017/5/13 17:22'

from django import forms
from captcha.fields import CaptchaField


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True,min_length=6)


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=5)
    captcha = CaptchaField(error_messages={'invalid': '验证码错误！'})


class ForgetPwdForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={'invalid': '验证码错误！'})


class ModifyPwdForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)

templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>链接失效</p>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}课程机构列表 - 慕学在线网{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
</head>
<body>
<!--头部内容-->
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>33333333</b></p></div>
					<!--登录后跳转-->
                    {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>bobby<img class="down fr" src="{% static 'images/top_down.png'%}"/></dd>
                                <dt><img width="20" height="20" src="../media/image/2016/12/default_big_14.png"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="../media/image/2016/12/default_big_14.png"/></dt>
	                                <dd>
	                                    <h2>django</h2>
	                                    <p>bobby</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="usercenter-info.html">进入个人中心</a>
	                                <a class="fr" href="/logout/">退出</a>
                                </div>
                            </div>
                        </div>
                        <a href="usercenter-message.html">
                            <div class="msg-num"> <span id="MsgNum">0</span></div>
                        </a>
                        {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}




				</div>
			</div>

            <div class="middle">
                <div class="wp">
                    <a href="index.html"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>


			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li ><a href="index.html">首页</a></li>
							<li class="active">
								<a href="course-list.html">
									公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
								</a>
							</li>
							<li >
								<a href="teachers-list.html">授课教师</a>
							</li>
							<li ><a href="{% url 'org:org_list' %}">授课机构</a></li>
						</ul>
					</div>
				</div>
			</nav>

			</div>
    </header>
</section>
<!--面包屑-->
{% block custom_bread %}
<section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
{% endblock %}
<!--页面body-->
{% block custom_content %}
{% endblock %}
<!--底部内容-->
<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
					<li class="code"><img src="{% static 'images/code.jpg' %}"/><p class="center">扫描关注微信</p></li>
					<li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/><p class="tell">33333333</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
                <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
			</div>
		</div>
	</footer>
<!--qq互联-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script  src="{% static 'js/plugins/laydate/laydate.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>

{% block custom_js %}
{% endblock %}
</body>
</html>

templates/course-comment.html
{% extends 'base.html' %}
{% block title %}公开课评论 - 慕学在线网{% endblock %}
{% load staticfiles %}

{% block custom_css %}
<link rel="stylesheet" href="{% static 'css/muke/course/learn-less.css' %}"/>
<link rel="stylesheet" href="{% static 'css/muke/course/course-comment.css' %}"/>
<link rel="stylesheet" href="{% static 'css/muke/base.css' %}">
<link rel="stylesheet" href="{% static 'css/muke/common-less.css' %}">
<link rel="stylesheet" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'courses:course_list' %}">公开课程</a> > </li>
                <li><a href="{% url 'courses:course_detail' course.id %}">课程详情</a> > </li>
                <li>课程评论</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block custom_content %}
<div id="main">
  <div class="course-infos">
    <div class="w pr">
      <div style="height: 15px" class="path">
      </div>
      <div class="hd">
        <h2 class="l">{{ course.name }}</h2>
      </div>
      <div class="statics clearfix">
        <div class="static-item ">
          <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
          <span class="meta">难度</span>
          <em></em>
        </div>
        <div class="static-item static-time">
          <span class="meta-value">{{ course.learn_times }}分钟</span>
          <span class="meta">时长</span>
          <em></em>
        </div>
        <div class="static-item">
          <span class="meta-value"><strong>{{ course.students }}</strong></span>
          <span class="meta">学习人数</span>
          <em></em>
        </div>
      </div>
    </div>
  </div>
  <div class="course-info-main clearfix w has-progress">

    <div class="info-bar clearfix">
      <div class="content-wrap clearfix">
        <div class="content">
          <div class="mod-tab-menu">
            <ul class="course-menu clearfix">
              <li><a class="ui-tabs-active " id="learnOn" href="{% url 'courses:course_info' course.id %}"><span>章节</span></a></li>
              <li><a id="commentOn" class="active" href="{% url 'courses:course_comment' course.id %}"><span>评论</span></a></li>
            </ul>
          </div>

          <!--发布评论-->
          <div id="js-pub-container" class="issques clearfix js-form">
            <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
              <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！"></textarea>
            </div>
            <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
            <p class="global-errortip js-global-error"></p>
          </div>
          <div id="course_note">
            <ul class="mod-post" id="comment-list">
              {#   课程评论  #}
              {% for user_comment in all_comments %}
              <li class="post-row">
                <div class="media">
                  <span target="_blank">
                    <img src='{{ MEDIA_URL }}{{ user_comment.user.image }}' width='40' height='40'/>
                  </span>
                </div>
                <div class="bd">
                  <div class="tit">
                    <span target="_blank">{{ user_comment.user.username }}</span>
                  </div>
                  <p class="cnt">{{ user_comment.comments }}</p>
                  <div class="footer clearfix">
                    <span title="创建时间" class="l timeago">{{ user_comment.add_time }}</span>
                  </div>
                </div>
              </li>
              {%  endfor %}

            </ul>
          </div>

        </div>
        <div class="aside r">
          <div class="bd">

            <div class="box mb40">
              <h4>资料下载</h4>
            {#  资料下载   #}
              <ul class="downlist">
                {% for course_resource in all_resources %}
                <li>
                  <span><i class="aui-iconfont aui-icon-file"></i>{{ course_resource.name }}</span>
                  <a href="{{ MEDIA_URL }}{{ course_resource.download }}" class="downcode" target="_blank">下载</a>
                </li>
                {% endfor %}
              </ul>
            </div>
            <div class="box mb40">
              <h4>讲师提示</h4>
              <div class="teacher-info">
                <a href="/u/315464/courses?sort=publish" target="_blank">
                  <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80'/>
                </a>
                <span class="tit">
                  <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
                </span>
                <span class="job">{{ course.teacher.work_position }}</span>
              </div>
              <div class="course-info-tip">
                <dl class="first">
                  <dt>课程须知</dt>
                  <dd class="autowrap">{{ course.youneed_konw }}</dd>
                </dl>
                <dl>
                  <dt>老师告诉你能学到什么？</dt>
                  <dd class="autowrap">{{ course.teacher_tell }}</dd>
                </dl>
              </div>
            </div>


            <div class="cp-other-learned  js-comp-tabs">
              <div class="cp-header clearfix">
                <h2 class="cp-tit l">该课的同学还学过</h2>
              </div>
              <div class="cp-body">
                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                  <!-- img 200 x 112 -->
                  <ul class="other-list">
                    {% for relate_course in relate_courses %}
                    <li class="curr">
                      <a href="{% url 'courses:course_detail' relate_course.id %}" target="_blank">
                        <img src="{{ MEDIA_URL }}{{ relate_course.image }}"  alt="{{ relate_course.name }}" />
                        <span class="name autowrap">{{ relate_course.name }}</span>
                      </a>
                    </li>
                    {% endfor %}
                  </ul>
                </div>
                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                  <ul class="other-list">
                    <li class="curr">
                      <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                        <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                        <span class="name autowrap">Java工程师</span>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
      <div class="clear"></div>

    </div>

  </div>
</div>
{% endblock %}

{% block custom_js %}
<script>
//添加评论
$('#js-pl-submit').on('click', function () {
    var comments = $("#js-pl-textarea").val()
    if (comments == "") {
        alert("评论不能为空")
        return
    }
    $.ajax({
        cache: false,
        type: "POST",
        url: "{% url 'courses:add_comment' %}",
        data: {course_id: {{ course.id }}, comments: comments},
        async: true,
        beforeSend: function (xhr, settings) {
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function (data) {
            if (data.status == 'fail') {
              if (data.msg == '用户未登录') {
                  window.location.href = "{% url 'login' %}";
              } else {
                  alert(data.msg)
              }
            } else if (data.status == 'success') {
                alert('评论成功！')
                window.location.reload();//刷新当前页面.
            }
        },
        error: function(error) {
          alert('ajax 失败!')
        }
    });
});
</script>
{% endblock %}

templates/course-video.html
{% extends 'base.html' %}
{% block title %}公开课视频信息 - 慕学在线网{% endblock %}
{% load staticfiles %}

{% block custom_css %}
  <link rel="stylesheet" href="{%  static 'css/muke/base.css' %}"/>
  <link rel="stylesheet" href="{%  static 'css/muke/common-less.css' %}"/>
  <link rel="stylesheet" href="{%  static 'css/muke/course/learn-less.css' %}"/>
  <link rel="stylesheet" href="{%  static 'css/aui.css' %}"/>
  <link rel="stylesheet" href="{%  static 'css/mooc.css' %}"/>
  <link rel="stylesheet" href="{%  static 'css/muke/course/common-less.css' %}">
{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'courses:course_list' %}">公开课程</a> > </li>
                <li><a href="{% url 'courses:course_detail' course.id %}">课程详情</a> > </li>
                <li>章节信息</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block custom_content %}
  <div id="main">
  <div class="course-infos">
    <div class="w pr">
      <div style="height: 15px" class="path">
      </div>
      <div class="hd">
        <h2 class="l">{{ course.name }}</h2>
      </div>
      <div class="statics clearfix">
        <div class="static-item ">
          <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
          <span class="meta">难度</span>
          <em></em>
        </div>
        <div class="static-item static-time">
          <span class="meta-value">{{ course.learn_times }}分钟</span>
          <span class="meta">时长</span>
          <em></em>
        </div>
        <div class="static-item">
          <span class="meta-value"><strong>{{ course.students }}</strong></span>
          <span class="meta">学习人数</span>
          <em></em>
        </div>
      </div>
    </div>
  </div>
  <div class="course-info-main clearfix w has-progress">

    <div class="info-bar clearfix">
      <div class="content-wrap clearfix">
        <div class="content">
          <div class="mod-tab-menu">
            <ul class="course-menu clearfix">
              <li><a class="ui-tabs-active active" id="learnOn" href="{% url 'courses:course_info' course.id %}"><span>章节</span></a></li>
              <li><a id="commentOn" class="" href="{% url 'courses:course_comment' course.id %}"><span>评论</span></a></li>
            </ul>
          </div>
          <div id="notice" class="clearfix">
            <div class="l"><strong>课程公告:</strong> <a href="javascript:void(0)"></a></div>
          </div>

          <div class="mod-chapters">
            {#     章节信息       #}
            {% for lesson in course.get_course_lesson %}
              <div class="chapter chapter-active">
              <h3>
                <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
              </h3>
              <ul class="video">
                {% for video in lesson.get_lesson_video %}
                <li>
                  <a target="_blank" href='{% url 'courses:video_play' video.id %}' class="J-media-item studyvideo">
                    {{ video.name }}&nbsp;（{{ video.learn_times }}）
                    <i class="study-state"></i>
                  </a>
                </li>
                {% endfor %}
              </ul>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="aside r">
          <div class="bd">

            <div class="box mb40">
              <h4>资料下载</h4>
            {#  资料下载   #}
              <ul class="downlist">
                {% for course_resource in course_resources %}
                <li>
                  <span><i class="aui-iconfont aui-icon-file"></i>{{ course_resource.name }}</span>
                  <a href="{{ MEDIA_URL }}{{ course_resource.download }}" class="downcode" target="_blank">下载</a>
                </li>
                {% endfor %}
              </ul>
            </div>
            <div class="box mb40">
              <h4>讲师提示</h4>
              <div class="teacher-info">
                <a href="/u/315464/courses?sort=publish" target="_blank">
                  <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80'/>
                </a>
                <span class="tit">
                  <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
                </span>
                <span class="job">{{ course.teacher.work_position }}</span>
              </div>
              <div class="course-info-tip">
                <dl class="first">
                  <dt>课程须知</dt>
                  <dd class="autowrap">{{ course.youneed_konw }}</dd>
                </dl>
                <dl>
                  <dt>老师告诉你能学到什么？</dt>
                  <dd class="autowrap">{{ course.teacher_tell }}</dd>
                </dl>
              </div>
            </div>


            <div class="cp-other-learned  js-comp-tabs">
              <div class="cp-header clearfix">
                <h2 class="cp-tit l">该课的同学还学过</h2>
              </div>
              <div class="cp-body">
                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                  <!-- 学过其他的课程循环 -->
                  <ul class="other-list">
                    {% for relate_course in relate_courses %}
                    <li class="curr">
                      <a href="{% url 'courses:course_detail' relate_course.id %}" target="_blank">
                        <img src="{{ MEDIA_URL }}{{ relate_course.image }}"  alt="{{ relate_course.name }}" />
                        <span class="name autowrap">{{ relate_course.name }}</span>
                      </a>
                    </li>
                    {% endfor %}
                  </ul>
                </div>
                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                  <ul class="other-list">
                    <li class="curr">
                      <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                        <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                        <span class="name autowrap">Java工程师</span>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
      <div class="clear"></div>

    </div>

  </div>
</div>
{% endblock %}